modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="jujutsucraft"
version="6"
displayName="jujutsu_craft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="orca, MCreator"

[[dependencies.jujutsucraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"


[[dependencies.jujutsucraft]]
    modId="jujutsuanimation"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


